services:
    dev:
        env_file:
            - .env
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        depends_on:
            - mongo
            - db_stats
        ports:
            - '${API_PORT}:${API_PORT}'
        volumes:
            - .:/usr/src/app
    prod:
        env_file:
            - .env
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        depends_on:
            - mongo
        ports:
            - '${API_PORT}:${API_PORT}'
    mongo:
        image: mongo
        volumes:
            - database:/data/db
    db_stats:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - '8081:8081'
volumes:
    database:
